language: python
python:
- '3.7'
dist: xenial
sudo: true
before_install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: setup tests
    script: echo $TRAVIS_BUILD_NUMBER
  - stage: run tests
    script: pytest
  - stage: build code
    script: bash build_script.sh
  - stage: upload release
    script: echo "uploading to github"
    deploy:
      provider: releases
      api_key:
        secure: "$GITHUB_OAUTH_TOKEN"
      file: python-app-*.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
