language: python
python:
  - "3.7"
dist: xenial
sudo: true
# command to install dependencies
before_install:
    - pip install -r requirements.txt
jobs:
  include:
    - stage: setup tests
      script: echo $TRAVIS_BUILD_NUMBER
    - stage: run tests
      script: pytest
    - stage: build code
      script: bash build_script.sh
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "python-app-$TRAVIS_BUILD_NUMBER.tar.gz"
  file_glob: true
  file: python-app-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
